name: Deploy to GAS

on:
  push:
    branches:
      - main

concurrency:
  group: mail-convert-forward-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Create .clasprc.json
        # echo だとJSONが壊れやすいから、ヒアドキュメント形式に変更
        run: |
          cat <<EOF > ~/.clasprc.json
          ${{ secrets.CLASP_RC }}
          EOF

      - name: Deploy
        run: clasp push -f
        # working-directory: src
